default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] || Rails.application.credentials.DATABASE_NAME %>
  username: <%= ENV['DATABASE_USER'] || Rails.application.credentials.DATABASE_USER %>
  password: <%= ENV['DATABASE_PASSWORD'] || Rails.application.credentials.DATABASE_PASSWORD %>
  host: <%= ENV['DATABASE_HOST'] || Rails.application.credentials.DATABASE_HOST %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: r00t
  password: 1amr00t
  host: localhost
  database: jwt_plus_oauth_authentication_development

test:
  <<: *default
  username: r00t
  password: 1amr00t
  host: localhost
  database: jwt_plus_oauth_authentication_test

production:
  <<: *default
  database: jwt_plus_oauth_authentication_production
  username: jwt_plus_oauth_authentication
  password: <%= ENV["JWT_PLUS_OAUTH_AUTHENTICATION_DATABASE_PASSWORD"] %>
